#pragma once

#define BOW_HEIGHT 200
#define BOW_LEN 60
#define BOW_COLOR glm::vec3((float)94/255, (float)38/255, (float)18/255)
#define BOW_MOVEMENT_TRANSLATE_FACTOR 100

#define ARROW_LEN 125
#define ARROW_VELOCITY_FACTOR 7
#define ARROW_COLOR glm::vec3((float)210/255 ,(float)105/255 ,(float)30/255)
#define ARROW_ANGLE_FACTOR 0.4
#define ARROW_TIP_WIDTH 15

#define BALLON_HEIGHT 70
#define BALLON_WIDTH 40
#define BALLONS_FIELD_OFFSET 300
#define BALLONS_SCALE_FACTOR 5
#define RED_BALLON_COLOR glm::vec3(1, 0, 0)
#define RED_BALLON_SCORE 1
#define YELLOW_BALLON_COLOR glm::vec3(1,1,0)
#define YELLOW_BALLON_SCORE -1

#define POWER_BAR_HEIGHT 30
#define POWER_BAR_LENGTH 5
#define POWER_BAR_SCALE_FACTOR 20
#define POWER_BAR_POS_X 10
#define POWER_BAR_POS_Y 10
#define POWER_BAR_COLOR glm::vec3(1, 0, 0)

#define SHURIKEN_COLOR glm::vec3(0,0,0)
#define SHURIKEN_LEN 50
#define SHURIKEN_SCORE 2
#define SHURIKEN_UP_PADDING 50 /*shuriken can t go higher than res.y - UP_PADDING*/
#define SHURIKEN_DOWN_PADDING 50 /* shuriken can t go lower than DOWN_PADDING*/

#define HEART_COLOR glm::vec3(1,0,0)
#define HEART_HEIGHT 10
#define HEART_LEN 10
#define HEARTS_POS_X 330
#define HEARTS_POS_Y resolution.y - 25

#define DIGIT_HEIGHT 20
#define DIGIT_WIDTH 10
#define SCORE_POS_X 260
#define SCORE_POS_Y resolution.y - 35
#define SCOREBAR_HEIGHT 50
#define SCOREBAR_LENGTH resolution.x
#define SCOREBAR_COLOR  glm::vec3(0,0,0)

#define TEXT_COLOR glm::vec3(1,1,1)

#define SECONDS_BETWEEN_ARROWS 1 
#define SECONDS_FOR_MAX_POWER 2 /* mouse pressed for maximum arrow power */
#define BOW_LEFT_PADDING 10 /* distance from the bow and the left side of screen */

#define SECONDS_BETWEEN_RED_BALLONS_L1 3
#define SECONDS_BETWEEN_RED_BALLONS_L2 2
#define SECONDS_BETWEEN_RED_BALLONS_L3 2
#define SECONDS_BETWEEN_RED_BALLONS_L4 1.5
#define SECONDS_BETWEEN_RED_BALLONS_L5 1.5
#define SECONDS_BETWEEN_RED_BALLONS_L6 1

#define SECONDS_BETWEEN_YELLOW_BALLONS_L1 5
#define SECONDS_BETWEEN_YELLOW_BALLONS_L2 5
#define SECONDS_BETWEEN_YELLOW_BALLONS_L3 5
#define SECONDS_BETWEEN_YELLOW_BALLONS_L4 3
#define SECONDS_BETWEEN_YELLOW_BALLONS_L5 3
#define SECONDS_BETWEEN_YELLOW_BALLONS_L6 1.5

#define SECONDS_BETWEEN_SHURIKENS_L1 2
#define SECONDS_BETWEEN_SHURIKENS_L2 2
#define SECONDS_BETWEEN_SHURIKENS_L3 2
#define SECONDS_BETWEEN_SHURIKENS_L4 2
#define SECONDS_BETWEEN_SHURIKENS_L5 1.5
#define SECONDS_BETWEEN_SHURIKENS_L6 0.8

#define BALLONS_VELOCITY_FACTOR_L1 150
#define BALLONS_VELOCITY_FACTOR_L2 150
#define BALLONS_VELOCITY_FACTOR_L3 150
#define BALLONS_VELOCITY_FACTOR_L4 300
#define BALLONS_VELOCITY_FACTOR_L5 300
#define BALLONS_VELOCITY_FACTOR_L6 400

#define SHURIKEN_VELOCITY_FACTOR_L1 150
#define SHURIKEN_VELOCITY_FACTOR_L2 150
#define SHURIKEN_VELOCITY_FACTOR_L3 150
#define SHURIKEN_VELOCITY_FACTOR_L4 150
#define SHURIKEN_VELOCITY_FACTOR_L5 300
#define SHURIKEN_VELOCITY_FACTOR_L6 400

#define SHURIKEN_ROTATION_FACTOR_L1 5
#define SHURIKEN_ROTATION_FACTOR_L2 5
#define SHURIKEN_ROTATION_FACTOR_L3 5
#define SHURIKEN_ROTATION_FACTOR_L4 5
#define SHURIKEN_ROTATION_FACTOR_L5 8
#define SHURIKEN_ROTATION_FACTOR_L6 11

#define LVL1_MAX_SCORE 2
#define LVL2_MAX_SCORE 4
#define LVL3_MAX_SCORE 6
#define LVL4_MAX_SCORE 8
#define LVL5_MAX_SCORE 10
#define GRAVITY_ARROW_LVL 6 /* lvl that arrows have gravity applied */

#define BACKGROUND_COLOR glm::vec3((float)0/255, (float)255/255, (float)127/255)
